version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: app
        restart: unless-stopped
        command: sh -c "php artisan migrate"
        environment:
            DB_HOST: db
            DB_USERNAME: root
            DB_PASSWORD: password
            SESSION_DRIVER: redis
            REDIS_HOST: redis
        volumes:
            - ./:/var/www
            - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            -   db

    webserver:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        image: laravel-nginx
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./config/nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - app

    db:
        image: mysql:5.7.22
        platform: linux/x86_64
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - dbdata:/var/lib/mysql/

volumes:
    dbdata:
        driver: local
